### ISSUE TITLE
提取motion vetor耗时太久

### ISSUE THREAD

**Issue by wullia** [Sixkplus/TapLab#4]
作者您好
在复现您的论文的时候发现data loader提取motion vector速度很慢，测试视频需要将近十分钟左右才能完成motion vector和residual map的提取。请问是哪儿出现了问题吗？

**Comment by Sixkplus** [comment]
@wullia 你好，感谢提问！
关于Mv和Res的提取，考虑到代码实现方便与可读性，我们使用的是[coviar](https://github.com/chaoyuaw/pytorch-coviar) 编译的python版本，该版本并未使用硬解，并且相应代码效率不高，提取时间较长是正常情况，也因此我们推荐先进行离线提取和存储。如果想要在实际工程中使用，可以搜寻c++解码提取mv/res的脚本/调用硬件解码。

**Comment by wullia** [comment]
> @wullia 你好，感谢提问！
> 关于Mv和Res的提取，考虑到代码实现方便与可读性，我们使用的是[coviar](https://github.com/chaoyuaw/pytorch-coviar) 编译的python版本，该版本并未使用硬解，并且相应代码效率不高，提取时间较长是正常情况，也因此我们推荐先进行离线提取和存储。如果想要在实际工程中使用，可以搜寻c++解码提取mv/res的脚本/调用硬件解码。

感谢您的回复，也感谢您的杰出工作！
